require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Naming/MethodParameterName:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/FilePath:
  SpecSuffixOnly: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

RSpec/ExampleLength:
  Max: 20
