on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  release-please:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.ELLIOTS_TAXMAN_TOKEN }}
          release-type: ruby
          package-name: taxman
          version-file: lib/taxman/version.rb
